### ISSUE TITLE
Add .editorconfig to enforce tabs.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/bridge-ui#16]

**Comment by Tbaut** [comment]
Interrestingly, the linter is supposed to enforce that here:
https://github.com/paritytech/bridge-ui/blob/master/.eslintrc.json#L42 and here: https://github.com/paritytech/bridge-ui/blob/master/.eslintrc.json#L44

I'll dig a bit.

**Comment by tomusdrw** [comment]
Yeah, perhaps the linter is now fixing the tabs, but my editor keeps using spaces by default if `.editorconfig` is not present :)
